version: '3.7'

services:
  db:
    image: postgres:11-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432

  luigi:
    build: ./src
    command: python3 main.py
    volumes:
      - ./src:/src
    #   - static_volume:/src/staticfiles
    #   - media_volume:/src/media
    depends_on:
      - luigid
      - db

  luigid:
    build: ./src
    command: luigid --pidfile /tmp/luigid.pid --state-path /tmp/luigi-state.pickle
    volumes:
      - ./src:/src
    ports:
      - 8082:8082


volumes:
  postgres_data:
  static_volume:
