version: '3.7'

services:
  db:
    image: postgres:11-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  luigi:
    build: ./src
    command: python3 main.py --scheduler-host daemon MainFlow
    volumes:
      - ./src:/src
    #   - static_volume:/src/staticfiles
    #   - media_volume:/src/media
    depends_on:
      - daemon
      - db

  daemon:
    build: ./src
    command:
      - luigid
    volumes:
      - ./src:/src
    ports:
      - 8082:8082

volumes:
  postgres_data:
  static_volume:
